from enum import Enum


class STATES(Enum):
    QUALIFIER = "QUALIFIER"
    QUALIFIER_CLOSE = "QUALIFIER_CLOSE"
    SEPERATOR = "SEPERATOR"
    FIELD = "FIELD"
    FIELD_IN_QUALIFIER = "FIELD_IN_QUALIFIER"
    END = "END"
    INVALID = "INVALID"
