from enum import Enum


class States(Enum):
    NEW_FIELD = "NEW_FIELD"
    FIELD = "FIELD"
    FIELD_IN_QUALIFIER = "FIELD_IN_QUALIFIER"
    CANDIDATE_FIELD_END = "CANDIDATE_FIELD_END"
    CANDIDATE_ESCAPE = "CANDIDATE_ESCAPE"
    INVALID = "INVALID"
    END = "END"
